---
- hosts: localhost
  gather_facts: false
  name: NetApp Aggregate Create
  vars:
    hostname:
    username:
    password:
    aggrdataname:
    diskcount:
  tasks:
  - name: Create and Online New Data Aggregate
    na_ontap_aggregate:
      state: present
      service_state: online
      wait_for_online: true
      time_out: 300
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "{{ aggrdataname }}"
      disk_count: "{{ diskcount }}"
