---
- hosts: localhost
  gather_facts: false
  name: NetApp aggr create
  vars_prompt:
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
    clustername: SGL_CL_910-01 # Cluster Name
    aggrdataname: aggr1_SGL_CL_910_02_data # New Data Aggregate name
    diskcount: 5 # Number of disks to add to the Data Aggregate
  tasks:
- name: Create Aggregates and wait 5 minutes until aggregate is online
  netapp.ontap.na_ontap_aggregate:
    state: present
    service_state: online
    name: ansibleAggr
    disk_count: 1
    wait_for_online: True
    time_out: 300
    snaplock_type: non_snaplock
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
