---
- hosts: localhost
  gather_facts: false
  name: NetApp Aggregate Create
  vars:
    hostname: 192.168.10.52
    username: ansible
    password: Admin12.
    aggrdataname: aggr_prueba
    diskcount: 5
  tasks:
  - name: Create and Online New Data Aggregate
    na_ontap_aggregate:
      state: present
      service_state: online
      wait_for_online: true
      time_out: 300
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "{{ aggrdataname }}"
      disk_count: "{{ diskcount }}"
