---
- hosts: localhost
  tasks:
    - name: Create Aggregates and wait 5 minutes until aggregate is online
      netapp.ontap.na_ontap_aggregate:
        state: present
        service_state: online
        wait_for_online: True
        time_out: 300
        snaplock_type: non_snaplock
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        name: "{{ aggrdataname }}"
        disk_count: "{{ diskcount }}"
