---
- hosts: localhost
  gather_facts: false
  name: NetApp NFS System Setup
  vars:
    login: &login
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
  task:   
  - name: Create cifs_server
    netapp.ontap.na_ontap_cifs_server:
      state: present
      name: data2
      vserver: svm_CIFS
      service_state: stop
      <<: *login
    
  - name: Start cifs_server
    netapp.ontap.na_ontap_cifs_server:
    state: present
    name: data2
    vserver: svm_CIFS
    service_state: started
    <<: *login
