---
- hosts: localhost
  gather_facts: false
  name: NetApp CIFS Setup
  vars:
    login: &login
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
    svmname: svm_CIFS # SVM or Vserver name
    rootvolname: svm_CIFS_root # SVM root vol name
    rootvolaggr: aggr1_SGL_CL_910_01_data # Which aggregate to place the SVM root vol
    rootvolsecurity: mixed # SVM Root vol security stype
    allowedaggrs: aggr1_SGL_CL_910_01_data # Allowed SVM data Aggregates
    allowedprotocols: cifs # Allowed SVM Protocols
    cifsvolname: CIFS_vol1 # First NFS Vol withint your SVM
    cifsaggr: aggr1_SGL_CL_910_01_data # Which Aggregate to place the CIFS Vol on
    cifsvolsize: 10 # CIFS Vol Size GB
    lifinterfacename: cifs_lif01 # SVM CIFS Lif name
    lifhomeport: e0d # Home port for SVM CIFS Lif
    lifhomenode: SGL_CL_910-01 # Home node for SVM CIFS Lif
    lifaddress: 192.168.2.52 # SVM NFS Lif IP Address
    lifnetmask: 255.255.255.0 # SVM NFS Lif Subnet
    vservername: svm_CIFS # SVM or Vserver Name
  tasks:
  - name: Create Vserver
    na_ontap_svm:
      state: present
      name: "{{ vservername }}"
      root_volume: "{{ rootvolname }}"
      root_volume_aggregate: "{{ rootvolaggr }}"
      root_volume_security_style: "{{ rootvolsecurity }}"
      aggr_list: "{{ allowedaggrs }}"
      allowed_protocols: "{{ allowedprotocols }}"
      <<: *login
   
  - name: Create CIFS LIF
    na_ontap_command:
      command: ['network', 'interface', 'create', '-vserver', '"{{ vservername }}"', '-home-node', '"{{ lifhomenode }}"', '-home-port', '"{{ lifhomeport }}"', '-data-protocol', 'cifs', '-failover-policy', 'system-defined', '-firewall-policy', 'data', '-lif', '"{{ lifinterfacename }}"']
      privilege: admin
      <<: *login
