---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files: "{{ file }}"
  vars:
    login: &login
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  name: "Build cluster: {{ cluster }}"
  tasks:
  - name: create cluster
    na_ontap_cluster:
      state: present
      cluster_name: "{{ cluster }}"
      hostname: "{{ node1.dhcp_ip }}"
      <<: *login
  - name: "Join Node to {{ cluster }}"
    na_ontap_cluster:
        state: present
        cluster_ip_address:  169.254.31.132
        #cluster_name: "{{ cluster }}"
        hostname: "{{ node1.dhcp_ip }}"
        <<: *login
  - name: Create cluster mgmt lif
    na_ontap_interface:
      state: present
      interface_name: "{{ cluster }}_mgmt"
      vserver: "{{ cluster }}"
      address: "{{ cluster_mgmt }}"
      netmask: 255.255.255.0
      role: cluster-mgmt
      home_node: "{{ cluster }}-01"
      home_port: e0c
      hostname: "{{ node1.dhcp_ip }}"
      <<: *login
  - name: Create User
    na_ontap_user:
      state: present
      name: admin
      applications: ssh,console,http,ontapi,service-processor
      authentication_method: password
      role_name: admin
      vserver: "{{ cluster }}"
      hostname: "{{ cluster_mgmt }}"
      <<: *login
  - name: remove auto mgmt lif
    na_ontap_interface:
      state: absent
      interface_name: "{{ cluster }}-01_mgmt_auto"
      vserver: "{{ cluster }}"
      hostname: "{{ cluster_mgmt }}"
      <<: *login

    
    
