---
- hosts: localhost
  name: "Build cluster: {{ cluster }}"
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: create cluster
    na_ontap_cluster:
      use_rest: Always
      https: true
      validate_certs: false
      state: present
      cluster_name: "{{ cluster }}"
      hostname: "{{ node1_dhcp_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
