---
- hosts: localhost
  gather_facts: false
  name: NetApp CIFS Setup
  vars:
    login: &login
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
    
  task:  
- name: Assign specified total disks to node
  netapp.ontap.na_ontap_disks:
    node: SGL_CL_910-01
    disk_count: 30
    disk_type: FCAL
    min_spares: 0
    hostname: "{{ hostname }}"
    <<: *login
