---
- hosts: localhost
  gather_facts: false
  name: NetApp Volume
  vars:
    login: &login
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
  tasks:
    - name: Get Volume 'test123'
      VolumeModule: action=get name=test123
      register : jsonResult
      <<: *login

    - name: print the Volume key
      debug: msg="{{ jsonResult.meta.result.records[0].key}}"

    - name: print the job key
      debug : msg="{{ jsonResult }}"

    - name: loop for status
      JobScheduleModule: action=get key={{ jsonResult }}
      register : jsonResult
      until:  (jsonResult.meta.result.records[0].status == "COMPLETED") or (jsonResult.meta.result.records[0].status == "FAILED")
      retries: 5
      delay: 10
      <<: *login
