---
- hosts: localhost
  name: NetApp licensing
  vars:
   login: &login
   hostname: 192.168.10.146
    username: admin
    password: Admin12.
    https: true
    validate_certs: false
    clustername: SNGL-CL-LAB
  tasks:
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      cluster_name: "{{ clustername }}"
      license_code: "{{ item }}"
      <<: *login
   loop:
     - YVUCRRRRYVHXCFABGAAAAAAAAAAA
     - WKQGSRRRYVHXCFABGAAAAAAAAAAA
     - SOHOURRRYVHXCFABGAAAAAAAAAAA
     - YBSOYRRRYVHXCFABGAAAAAAAAAAA
     - KQSRRRRRYVHXCFABGAAAAAAAAAAA
     - MBXNQRRRYVHXCFABGAAAAAAAAAAA
     - QDDSVRRRYVHXCFABGAAAAAAAAAAA
     - CYAHWRRRYVHXCFABGAAAAAAAAAAA
     - GUJZTRRRYVHXCFABGAAAAAAAAAAA
     - OSYVWRRRYVHXCFABGAAAAAAAAAAA
     - UZLKTRRRYVHXCFABGAAAAAAAAAAA
     - EJFDVRRRYVHXCFABGAAAAAAAAAAA
     
     
