---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: run ontap rest cli command
    na_ontap_rest_cli:
      use_rest: Always
      https: true
      validate_certs: false
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      command: 'license'
      verb: 'GET'
    register: ontap_info
  - debug: var=ontap_info
