---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: run ontap cli command
    netapp.ontap.na_ontap_command:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      command: ['network', 'interface', 'show', '-vserver', 'Cluster', '-lif', 'clus1', '-fields', 'address']
      privilege: 'admin'
      return_dict: true
