---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
    - name: Get ONTAP Intra Cluster IP Address
      na_ontap_info:
        gather_subset: "net_interface_info"
        use_rest: auto
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
      register: ontap_info
    - set_fact: 
        netapp_intra_cluster_address: "{{ ontap_info.ontap_info.net_interface_info }}"
    - debug: var=netapp_intra_cluster_address
