---
- hosts: localhost
  tasks:
    - name: Get ONTAP Inter Cluster IP Address
      na_ontap_info:
        gather_subset: "net_interface_info"
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
      register: ontap_info
    - set_fact: 
        netapp_inter_cluster_address: "{{ ontap_info.ontap_info.net_interface_info[ netapp_cluster_name + '-01_clus1'].address }}"
    - debug: var=netapp_inter_cluster_address
