---
- hosts: localhost
  tasks:
    - name: Get Network Info
      na_ontap_info:
        gather_subset: "net_interface_info"
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
    - debug: var=ontap_info.ontap_info.net_interface_info.SGL_CL_910-01_mgmt1.address
