---
- hosts: localhost
  tasks:
    - name: Get Network Info
      na_ontap_info:
        gather_subset: "net_interface_info"
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
      register: ontap_info
    - debug: 
        msg:
          address: "{{ ontap_info.ontap_info.net_interface_info.['\"{{ netapp_cluster_name }}\"-01_clus1'].address }}"
