---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
    - name: Get ONTAP Intra Cluster IP Address
      na_ontap_rest_info:
        gather_subset: "cluster/nodes"
        use_rest: Always
        https: true
        validate_certs: false
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
      register: ontap_info
    - debug: var=ontap_info
