---
- hosts: localhost
  gather_facts: false
  name: NetApp Info
  vars:
    login: &login
     hostname: 192.168.10.52 # NetApp Cluster IP
     username: ansible # Cluster User
     password: Admin12. # Cluster Password
     https: true
     validate_certs: false
  tasks:  
   - name: reading the csv file
     read_csv:
      path: 192.168.10.10\usario_list.csv
     register: usario_list
     delegate_to: localhost

   - name: display user_list data
     debug:
      var: usario_list.list
      
